### ISSUE TITLE
RTL88x2BU-Linux-Driver fails to compile with Linux 6.5.0-10-generic from Ubuntu 23.10 (Mantic Minotaur)

### ISSUE THREAD

**Issue by eurbah** [RinCat/RTL88x2BU-Linux-Driver#215]
On Linux 6.5.0-10-generic from Ubuntu 23.10 (Mantic Minotaur), kernel headers :

-  do NOT define REGULATORY_IGNORE_STALE_KICKOFF anymore,
-  have added argument(s) to function ‘cfg80211_ch_switch_started_notify :

```
$ grep  -A 7  cfg80211_ch_switch_started_notify  /usr/src/linux-headers-6.5.0-10/include/net/cfg80211.h
 * cfg80211_ch_switch_started_notify - notify channel switch start
 * @dev: the device on which the channel switch started
 * @chandef: the future channel definition
 * @link_id: the link ID for MLO, must be 0 for non-MLO
 * @count: the number of TBTTs until the channel switch happens
 * @quiet: whether or not immediate quiet was requested by the AP
 * @punct_bitmap: the future puncturing bitmap
 *
--
void cfg80211_ch_switch_started_notify(struct net_device *dev,
				       struct cfg80211_chan_def *chandef,
				       unsigned int link_id, u8 count,
				       bool quiet, u16 punct_bitmap);
```

Extract from RTL88x2BU-Linux-Driver make.log :
```
/var/lib/dkms/rtl88x2bu/5.13.1/build/os_dep/linux/wifi_regd.c: In function 'rtw_regd_init':
/var/lib/dkms/rtl88x2bu/5.13.1/build/os_dep/linux/wifi_regd.c:409:36: error: 'REGULATORY_IGNORE_STALE_KICKOFF' undeclared (first use in this function)
  409 |         wiphy->regulatory_flags |= REGULATORY_IGNORE_STALE_KICKOFF;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/var/lib/dkms/rtl88x2bu/5.13.1/build/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_ch_switch_notify’:
/var/lib/dkms/rtl88x2bu/5.13.1/build/os_dep/linux/ioctl_cfg80211.c:458:17: error: too few arguments to function ‘cfg80211_ch_switch_started_notify’
  458 |                 cfg80211_ch_switch_started_notify(adapter->pnetdev, &chdef, 0, 0, false);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/rtl88x2bu/5.13.1/build/include/osdep_service_linux.h:98,
                 from /var/lib/dkms/rtl88x2bu/5.13.1/build/include/osdep_service.h:54,
                 from /var/lib/dkms/rtl88x2bu/5.13.1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl88x2bu/5.13.1/build/os_dep/linux/ioctl_cfg80211.c:17:
./include/net/cfg80211.h:8592:6: note: declared here
 8592 | void cfg80211_ch_switch_started_notify(struct net_device *dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Can you correct these issues and publish a new driver version which can be downloaded ?

Thank you in advance.

**Comment by RinCat** [comment]
This one has been fixed 4 months ago, please update your local source code.
